spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mall_admin?useUnicode=true&characterEncoding=utf8mb4&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
  data:
    redis:
      host: redis
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

gateway:
  base-url: http://gateway-service:8080

logging:
  level:
    com.mall.admin: INFO
